ssbc/ssb-keys

index.js

This allows the ssb-config object to be passed directly to loadOrCreateSync (and the other key methods)
The benefit here is mainly to simplify examples downstream (in particular ssb-client), and encode conventions about where the secret file is exactly in one place.

allow key load/create calls to take config object

---

browser-sodium.js
eccjs.js
index.js
package.json
sodium.js
test/index.js

This adds [ed25519](http://ed25519.cr.yp.to/) via nacl.
It's at least twice as fast as k256 from sjcl, and doesn't have side-channel leaks...
Side channels (when you gain information about the key by examining, eg, how other software runs on the same computer... is probably a big risk in JS crypto, because it would be pretty easy to get more js running on the same computer...)
Also, this makes https://github.com/ssbc/scuttlebot/pull/192 take only 5 seconds!!!
Another benefit is that the ed25519 public key is only 32 bytes long (same size as a blake2s hash) so we can just put it in every message instead of looking up, which could make the validation algorithm simpler too!

tracking PR: add nacl crypto

---

index.js
test/index.js

Update to use link sigils.
Still figuring out how deep the changes need to be here. Currently, this PR affects key-generation by prepending an `@` to the `id` of a key object, and leaving `public` and `private` alone.

Sigil support

---

index.js

!! I discovered this after I installed the latest patchwork from npm; it dumped my private key into bash during startup.

Remove logging of keys to stdout

---

index.js
package.json

this makes eccjs into a devdep only. I wanted to leave it in the tests, so that we still have the idea of a switchable signature. but, since we don't want to use sjcl, we can drop it, and that will resolve this issue: https://github.com/ssbc/ssb-keys/issues/21

make eccjs a devdep

---

index.js
test/weird.js

This will fix the fork that @wanderer found. https://github.com/ssbc/patchwork/issues/343#issuecomment-201381664
Turns out there are lots of messages that hash wrong, but we only recently discovered this, because the default behavior only changed in node@6, which so far only dust has used,
(actually, node@6 isn't even an official version yet!)
This change will make it hash consistently in node@6, as it did in node@<6
I think this should be a discussion PR for now, if @wanderer can downgrade to node@5, and we can figure out how to upgrade to a new hash/encoding that doesn't have this unfortunate bug.

repair the fork

---

index.js

this works around a very weird electron bug.
https://github.com/electron/electron/issues/5544
just a patch

hack to make base64 decoding work on electron

---

index.js
package.json

I was going to use ssb-keys for a personal project, and had a read through the code. Can I depend on the package, or should I duplicate the API myself? I mean, given that the api of this package seems pretty complete, I'd say yes, but it's still branded as ssb-*

Remove unused dependency ssb-ref

---

storage.js

To support environments like React Native's packager, which checks for strict mode, we need to avoid keywords like `private` or `public`.

Avoid reserved keywords in storage.js

---

storage.js

`fs.readFileSync` is not available in https://www.npmjs.com/package/level-filesystem which is what React Native uses when shimming `fs` (because it cannot support sync APIs). I figured that this line of code is checking (1) whether `fs` is available and (2) whether `fs` is actually a filesystem API. It seems for purpose (2) that `readFile` is enough. Or is there a reason for `readFileSync`?
With these changes, an `fs` object missing `readFileSync` would still work as long as `loadSync` is avoided and `load` is used instead.

Fix storage.js fallback logic to local-storage

---

sodium.js

To support environments like React Native's packager, which checks for strict mode, we need to avoid keywords like `private` or `public`.

Avoid reserved keywords in sodium.js

---

package.json
storage.js
test/fs.js

this seems like a very reasonable default for a function that deals with keyfile generation
also threw in a commit that actually runs all the tests in the `/tests` directory upon `npm run test`
fixes #44

prevent clobbering existing keys

---

util.js

This is a minor edit for clarity and should not give any change in behaviour of ssb-keys as it is now. 
For context see %rN1jBwjg3Zhz9qnEoj9gcx//uwKaKQzArVkwMUUiUtg=.sha256

id property is public key regardless of curve

---

README.md

There are more exported functions in the module than the README shows. I've tried to add the missing documentation for them but couldn't because I don't know crypto/sodium stuff. The roadblock is that the missing methods are little wrappers around `private-box` which unfortunately is out of sync with NPM. The version of that module on GH doesn't contain the stuff called by `ssb-keys`. Digging deeper into `node_modules`, I can see that these `private-box` functions are just wrappers around `libsodium` functions which I couldn't find documentation for. Kinda need help filling these last two methods in the README (they are tagged with `TODO:`).

adding missing docs but needs more work.

---

index.js

@keks and I discovered this simple change improves index building perf by 15% (on my laptop)
asymmetric operations are about 60 times more expensive than symmetric operations, and we do two of them, but this one is cachable.
@arj03 @staltz

cache curve key when decrypting, makes rebuilding indexing 15% faster.

---

README.md
index.js

This would be useful for my work in the Rusty Sunrise Choir.
If `ssb-keys` can do the conversion between key types then I can just pass down the correct key to my rust code.

Export function to convert from ed25519 secret to curve25519 secret

---

storage.js

Problem: I keep seeing new SSB users who want same-as and decide to
experiment with copying their secret file to multiple devices at the
same time. This seems like it should work, and this sort of hacky ethos
would usually be encouraged, but it's risky and will inevitably fork the
feed.
Solution: Rewrite the secret file to move the warnings to the top,
adding a warning about copying the secret file to a second device.
Result:
```
#
#
#
{
"curve": "ed25519",
"public": "evXQK4uP4BkgvpZuaIsPXzfNWPkRooxD4knkYuqRdIg=.ed25519",
"private": "H/99s8PVe9MgExXfI4uaVuHjAGdB45aB3cSgv/6cSp169dAri4/gGSC+lm5oiw9fN81Y+RGijEPiSeRi6pF0iA==.ed25519",
"id": "@evXQK4uP4BkgvpZuaIsPXzfNWPkRooxD4knkYuqRdIg=.ed25519"
}
#
#
```

Rewrite secret file to warn users against copying

---

.travis.yml
test/fs.js

Problem: It's really convenient to see test failures from GitHub and
it's no fun if you have to pull a branch and test them locally.
Solution: Add basic Travis CI integration so that our tests are run
automatically and we can see failures from the pull request page.

Add Travis CI for automated tests

---

index.js
local-storage.js
storage.js
test/box-unbox.js
test/fs.js
test/index.js

There are some unused variables, unused escape characters, and invalid
JS (e.g. reassignment with `var` prefix) that makes this module harder
to grok.
This commit applies the recommended ESLint ruleset to resolve these
problems.

Tidy with ESLint:Recommended

---

.travis.yml

Travis CI wasn't running for this repo, because there was an automatic migration from `master` to `main` as the default branch, but we didn't (manually) update the Travis config.

Point Travis CI to main, not master

---

package.json

We don't have package-lock.json and the `dependencies` are specified with a hat `^`, so this means the ranges are pretty loose.
[Tests are failing in `main`](https://github.com/ssb-js/ssb-keys/pull/70), and I realized that's because they are installing `chloride@2.3.0`, because we specified the range `"chloride": "^2.2.8"`.
This PR uses tilde instead of hat, to make the version range more narrow, and thus rejecting `chloride@2.3.0`, but sticking with `chloride@2.2.x`. The tests now pass. We should try to support `chloride@2.3.0` too, but that's another issue.

use tilde version range in package.json dependencies

---

.gitignore
package.json

This is a simple first-step code coverage addition to this repo. `nyc` is run prefixed to `tape test/*` and will simply run `tape` but at the end will report a summary of test coverage on the codebase.
It's clear that we have a lot of code not covered by tests. We should make more PRs to add tests and seek for 100% coverage, especially for ssb-keys which is a highly-depended-on module.

Add code coverage tooling

---

index.js
package.json
sodium.js
util.js

The constructor `new Buffer` is deprecated in modern versions of Node.js. We replaced these by `Buffer.from` and `Buffer.alloc` in secret-stack, but now we should do it here too. This PR also requires Node.js to be at least `5.10.0` (so does secret-stack already do that) in order to guarantee that we can use these Buffer factory functions.

replace Buffer constructor with modern Buffer factories

---

test/box-unbox.js
test/fs.js
test/index.js

Previously, public APIs `unboxKey`, `unboxBody`, `getTag` were untested, this PR adds some basic tests for those. Also, `loadOrCreate` got more tests for various cases when it loads or when it creates.
```
------------|---------|----------|---------|---------|----------------------------------------
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                      
------------|---------|----------|---------|---------|----------------------------------------
All files   |   81.41 |       68 |   86.05 |   87.65 |                                        
index.js   |      75 |    68.52 |      70 |   79.35 | 42,66-68,73-76,101,145,153-155,159-166 
sodium.js  |     100 |    83.33 |     100 |     100 | 10                                     
storage.js |   86.44 | …
```

test loadOrCreate, getTag, unboxKey, unboxBody

---

package.json
test/box-unbox.js
test/fs.js
test/index.js
test/secretbox.js

I think Dominic's style of writing tests usually involves `console.log`s sprinkled here and there while we debugged their outputs. That's okay for debugging tests when you're writing tests, but when you're just running the tests (that you already trust to be written correctly), you don't want to see all that input.
This PR puts a `if (process.env.VERBOSE_TESTS)` check before every `console.log` and then adds a new script `test-verbose` which has that env var enabled. Thus, when you run `npm test`, it will be "silent", but if you run `npm run test-verbose` it will give you all those console.log outputs. CI should use `npm test`.

create test-verbose script, make test script unverbose

---

test/index.js

Add more tests for `signObj` and `verifyObj`. To explicitly name the `hmac_key` argument, we can use `null` (some people do that), but we can also pass any falsy value.

add tests for sign and verify when hmac_key is falsy

---

package.json
test/secretbox.js

Hunting down some build errors, I noticed that the chloride dependency was out of date.  This brings it up to current and fixes a problem in the tests (where it was incorrectly passing a key of the wrong length) so that all tests pass.

Bump version of chloride to 2.4.0

---

test/fs.js

Full context is here: https://github.com/staltz/ssb-keys-neon/pull/25

test loadOrCreates treats path as file

---

test/box-unbox.js

`unbox` can do `unbox(cyphertext, alice.private)` **or** `unbox(cyphertext, alice)`, but we were only testing the former. This PR adds a test for the latter.

add test for box/unbox with imprecise args

---

package.json

Chloride 2.4.1 was just released which fixes an issue where errors were emitted which shouldn't have been:
https://github.com/ssb-js/chloride/commit/287922f20a94f02e0c3d6ce6cb8d6fb79d9e30a6
This bumps that dependency.

Bump version of chloride to 2.4.1

---

README.md
index.js
test/index.js

Context: we need to sign and verify strings for [rooms2 alias registration](https://ssb-ngi-pointer.github.io/rooms2/#alias-database).
Problem: `ssb-keys` implements `signObj` which works only on objects (by calling JSON.stringify), but there is actually already an implementation for `sign`, it's just not exported. Likewise for `verifyObj`.
Solution: export `sign` and `verify`.
1st commit adds a failing test, 2nd commit adds the implementation that makes tests pass.

tests for sign/verify functions

---

index.js
test/index.js

You can't current use verify if the signature is a buffer. This fixes that problem :)

A buffer looks like an object in js

---

README.md
index.js
package.json
test/index.js
util.js

**Context:** we're introducing new feed formats in ssb-db2, but to generate the keys for those feed formats, ...
**Problem:** we're calling `generate()` and then mutating the return value `keys` such that `keys.id` is an SSB URI for the corresponding feed type. Sad example: https://github.com/ssbc/ssb-db2/blob/f976aac9a4bd4ee804b9f4cd24511dec52cb5d9d/test/basic.js#L372-L376
**Solution:** this PR allows you to pass an argument to `generate()` informing it of which feed format this key is for, which then automatically determines what the `keys.id` should be.

allow generate() to return SSB URIs as keys.id

---

README.md
sodium.js
test/index.js

**Context:** For testing, it's worth using deterministic keys, but the API for passing a `seed` is a bit annoying because you have to craft a buffer yourself and it has to be 32 bytes long.
**Solution:** this PR allows the `seed` argument of `generate(curve, seed, feedFormat)` to be a string, which is then used to produce a 32-byte seed buffer regardless of the size of the seed string.

allow generate() seed arg to be a string
